# Generated by Django 4.0.3 on 2022-03-22 05:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0004_alter_food_image_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Items',
        ),
    ]
