# Generated by Django 4.0.3 on 2022-03-25 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0005_rename_cart_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('pay_on_delivery', models.BooleanField(default=False)),
                ('shipped', models.BooleanField(default=False)),
                ('order_received', models.BooleanField(default=False)),
                ('dish', models.ManyToManyField(to='Home.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
